[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:horizon]
command=php /var/www/html/artisan horizon
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/horizon.err.log
stdout_logfile=/var/log/supervisor/horizon.out.log

[program:scheduler]
command=/bin/sh -c "while true; do php /var/www/html/artisan schedule:run; sleep 60; done"
autostart=true
autorestart=true